import Head from 'next/head'
import Nav from '../components/nav'
import Remesa from '../components/remesa'
import Servicios from '../components/Servicios'
import Info from '../components/Info'
import Casino from '../components/Casino'
import Precios from '../components/Precios'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

     <main>
     <Nav/>
     <div className='bg-white mx-5 rounded-md shadow-2xl flex items-center'>
     <img src='https://www.svgrepo.com/show/422995/trophy-prize-medal-3.svg'></img>
     <h2 className='mx-3 my-3 font-medium text-xl'>Envía dinero con un mejor tipo de cambio y evita comisiones bancarias excesivas.</h2>
     </div>
    
<Remesa/>
<Servicios image="https://www.svgrepo.com/show/362035/visa-3.svg" text='Targetas Visa'/>
<Casino/>
<Info image='https://www.svgrepo.com/show/423679/store-verified-shopping.svg' text='En menos de 24 horas su familiar, amigo o asociado en Cuba recibirá los fondos transferidos hacia su tarjeta en CUP.'/>
<Info image='https://www.svgrepo.com/show/423693/discount-sign-money.svg' text='Tenemos la satisfacción de brindar el servicio con los impuestos más bajos en el mercado de las remesas.'/>
<Info image='https://www.svgrepo.com/show/423683/testimoni-hand-finger.svg' text='Su envío esta protegido con la mayor seguridad de la blockchain en nuestro sistema.'/>
<Info image='https://www.svgrepo.com/show/423681/payment-cards-money.svg' text='Con pocos datos, demoras innecesarias, seguridad y trazabilidad UD podrá enviar remesas a Cuba en criptomonedas sin preocupaciones.'/>
  <Precios/>
     </main>
    </div>
  )
}
